In [24]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import scipy
import math
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
from matplotlib import rc
from scipy.signal import find_peaks 
from cProfile import label

In [2]:
hbar = 1.05457*10**(-34) # J*s
c = 2.998*10**8 # m/s
u_to_kg = 1.6605*10**(-27)
pm_to_m = 10**(-12)
kT = 207 # cm^-1

In [ ]:
# 1) Calculate and plot a potential energy surface for HCl with your favorite electronic structure method

In [ ]:
# 2) Find the harmonic oscillator energy levels of HCl

In [ ]:
# 5a) Write a code that calculates anharmonic energy levels using the above expressions and the effect of the
#     step-up and step-down operators. You can limit the expansion to terms with m ≤ 4

In [11]:
def makeA(n):
    nums = np.arange(0, 2**n, 1, dtype=int)
    A = ((nums.reshape(-1, 1) & (2**np.arange(n))) != 0).astype(int)
    A[A==0] = -1
    return A

order = 4

A = makeA(order) #Example
print(A) #Print example

[[-1 -1 -1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1 -1]
 [ 1 -1  1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]
 [-1 -1 -1  1]
 [ 1 -1 -1  1]
 [-1  1 -1  1]
 [ 1  1 -1  1]
 [-1 -1  1  1]
 [ 1 -1  1  1]
 [-1  1  1  1]
 [ 1  1  1  1]]


In [ ]:
# Write a function that inputs a row in the A-matrix and a (ket) quantum number. The output should
# be the constant in front of the resulting state.

In [18]:
def up_down_operator(A_row, v):
    scalar = 1
    state = v
    for A in A_row:
        if A == -1:
            if state == 0:
                return 0, 0
            else:
                scalar *= np.sqrt(state)
                state += A
        else:
            scalar *=np.sqrt(state+1)
            state +=A
    return scalar, state

constant, state = up_down_operator(A[12], 0)
print(constant, state)

0 0


In [ ]:
# Write a function that generates a matrix for each order of (a† + a)^m for m ≥ 3 (the M-matrices). Start
# by generating empty matrix of size nbasis × nbasis, where nbasis is the number of basis functions. The
# basis will be: {|v⟩} = {|0⟩, |1⟩, |2⟩, ..., |nbasis⟩}. Then loop over all elements of the M-matrices, and insert
# the appropriate values obtained by applying the step-up and step-down operators in the matrix A (which
# depends on the order, m).

In [21]:
nbasis = 4

def makeM(nbasis, max_order):
    matrix_M = np.zeros((nbasis, nbasis))
    matrix_A = makeA(max_order)
    for row in matrix_A:
        temp_matrixM = np.zeros_like(matrix_M)
        for i in range(nbasis):
            for j in range(nbasis):
                scalar, acted_state = up_down_operator(row, i)
                if acted_state == j:
                    temp_matrixM[i][j] = scalar
        matrix_M += temp_matrixM
        # print(temp_matrixM)
    return matrix_M

In [22]:
test_M = makeM(nbasis, 4)
print(test_M)

[[ 3.          0.          8.48528137  0.        ]
 [ 0.         15.          0.         24.49489743]
 [ 8.48528137  0.         39.          0.        ]
 [ 0.         24.49489743  0.         75.        ]]


In [ ]:
# Add together the matrices for each order, with the multiplication factors in Eq. 1.2. 
# Remember that the order of the operators matter, a†a ̸= aa†

In [ ]:
def M_sum(omega, nbasis, max_order):
    M2 = hbar*omega*makeM(nbasis, 2)
    for order in range(3, max_order+1):
        matrixM = (1/math.factorial(order))*F(order)*((q_c/np.sqrt(2))**(order))*makeM(nbasis, order)
        

In [ ]:
# Diagonalize H = M2 +M3 +M4 + ...